### ISSUE TITLE
doc: add page Getting Started to Gitbook

### ISSUE THREAD

**Issue by n1c01a5** [feature-sh/bounties#1]
Take exemples from:
- [Solidity Docs](https://docs.soliditylang.org/en/v0.8.13/) For info, the used ReadTheDocs.
- [Sablier Finance](https://sablier.finance/).
- [Kleros](https://kleros.gitbook.io/docs/).

**Comment by n1c01a5** [comment]
Get 20 XDAI for this $docs (XDAI)

**Comment by Opixelum** [comment]
#5

**Comment by opixelum** [comment]
feat #5
