### ISSUE TITLE
feat: create new milestone every 2 weeks

### ISSUE THREAD

**Issue by opixelum** [feature-sh/bounties#19]
Parse milestone's name for giving the next sprint number.

**Comment by n1c01a5** [comment]
create this $feat for 30XDAI (xdai)

**Comment by opixelum** [comment]
$feat #27

**Comment by BLOCKCHAINDEVWEB** [comment]
I tested "Execute payment" from the Dashboard.

The [transaction ](https://blockscout.com/xdai/mainnet/tx/0xfa6ac57b159703cac090ca9b9f544bb9d636728dcadc793f1c13f70e0841882d) was successful but the message did not appear.

**Comment by n1c01a5** [comment]
@Opixelum did you get the reward ?

**Comment by n1c01a5** [comment]
Another thing, if you have some times can you check the "iteration label" to see if it's relevant to switch to it.
