### ISSUE TITLE
feat: add Readme to describe the organization

### ISSUE THREAD

**Issue by n1c01a5** [feature-sh/bounties#21]
See [How Customizing your Organization](https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/customizing-your-organizations-profile).

Think of the `README` as the elevator pitch for your project. Keep it concise and to the point

- [x] Don't list out all the functionalities of your project as the first thing in the `README`
  * Recommendations
    * Showing users all the options they can do with something will confuse and/or overwhelm them
    * The first example you show should be the absolute most basic example that is working and copy-and-paste-able. 
    * My definition of simplicity: something is simple when there is nothing left to take away from it
    * Don’t initially show users multiple ways of doing something. Show them only one way of doing it. Be careful which way you show them. Choose the way that they will use most of the time
    * It’s tempting to show your users all the things they can do with your project. In many cases, however, this will intimidate users (especially those that are new to the idea or the ecosystem)
- [x] Start by showing the most common functionalities first. If your project is an API, only initially show examples of the most common APIs that are used. If your project is an app, show screenshots of the pages that are most commonly used
- [ ] Include a live demo. A video is a thousand pictures and a picture is a thousand words
- [x] Communicate your [Value Proposition](#value-proposition)
- [x] Provide interactive examples. Having ready and runnable examples lowers the barrier to using and testing out your project
  * Recommendations
    * Web Apps: Provide links to the hosted version of your app

**Comment by n1c01a5** [comment]
create this $doc for 30XDAI (xdai)

**Comment by opixelum** [comment]
@n1c01a5 Impossible to embed a video unless it is uploaded on YouTube.

**Comment by Opixelum** [comment]
$feat #25

**Comment by opixelum** [comment]
$feat #25
